services:
  migrate:
    image: migrate/migrate
    depends_on:
      go_db:
        condition: service_healthy
        restart: true

    volumes:
      - ./db/migrations/:/migrations
    command: [ "-path", "/migrations", "-database", "postgres://postgres:1234@go_db:5432/contactListDB?sslmode=disable", "up" ]
    networks:
      - go-api-network
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 3s
      retries: 5
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    networks:
      - go-api-network

volumes:
  pgdata: {}

networks:
  go-api-network:
    driver: bridge
